# Generated by Django 5.0 on 2024-01-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='./static/')),
                ('file', models.FileField(upload_to='./files/')),
            ],
        ),
    ]
