# Generated by Django 5.0 on 2024-01-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_chatroom_file_alter_chatroom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
