# Generated by Django 5.0 on 2024-01-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_chatroom_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(blank=None, upload_to='./static/images'),
        ),
    ]
